student-s-progress--master/StudentsProgress/src/CoreLoginEfDbFirst/Pages/Home/Index.cshtml.cs
//-----------------------------------------------------------------------
// <copyright file="Index.cshtml.cs" company="None">
//     Copyright (c) Allow to distribute this code and utilize this code for personal or commercial purpose.
// </copyright>

//-----------------------------------------------------------------------

namespace StudentsProgress.Pages.Home
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authentication;
    using Microsoft.AspNetCore.Authentication.Cookies;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.RazorPages;

    /// <summary>
    /// Index page model class.
    /// </summary>
    [Authorize]
    public class IndexModel : PageModel
    {
        #region On Get method.

        /// <summary>
        /// On Get method.
        /// </summary>
        public void OnGet()
        {
            try
            {
            }
            catch (Exception ex)
            {
                // Info
                Console.Write(ex);
            }
        }

        #endregion

        #region Log Out method.

        /// <summary>
        /// POST: /Home/Index/LogOff
        /// </summary>
        /// <returns>Return log off action</returns>
        public async Task<IActionResult> OnPostLogOff()
        {
            try
            {
                // Setting.
                var authenticationManager = Request.HttpContext;

                // Sign Out.
                await authenticationManager.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch (Exception ex)
            {
                // Info
                throw ex;
            }

            // Info.
            return this.RedirectToPage("/Index");
        }

        #endregion
    }
}

student-s-progress--master/StudentsProgress/src/CoreLoginEfDbFirst/Pages/Home/Index.cshtml
@page 


@model StudentsProgress.Pages.Home.IndexModel

@{
    ViewBag.Title = "";
}

<h2>@ViewBag.Title.</h2>

<div class="jumbotron">
    <h1>Welcome</h1>
    <p class="lead">Login from "@User.Identity.Name" Account.</p>
</div>

<div class="row">
    <div class="col-md-8">
        <form method="post" role="form" class="form-horizontal">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button asp-page-handler="LogOff" class="btn btn-default">Log Off</button>
                </div>
            </div>
        </form>
    </div>
</div>